# Generated by Django 6.0.5 on 2026-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approval_level',
            field=models.CharField(choices=[('MENTOR', 'Mentor Only'), ('HOD', 'Up to HOD'), ('DEAN', 'Up to Dean')], default='DEAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_MENTOR', 'Pending Mentor Approval'), ('PENDING_STUDENT_HOD', 'Pending Student Request to HOD'), ('PENDING_HOD', 'Pending HOD Approval'), ('PENDING_STUDENT_DEAN', 'Pending Student Request to Dean'), ('PENDING_DEAN', 'Pending Dean Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_MENTOR', max_length=20),
        ),
    ]
